# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/lib"
    exclude-paths:
      - "examples/*"
    schedule:
      interval: daily
      time: "11:00"
    commit-message:
      include: scope
      prefix: "fix"
      prefix-development: "chore"
    groups:
      react:
        patterns:
          - "@types/react*"
          - "react*"
      vite:
        patterns:
          - "@vitejs/*"
          - "vite"
          - "vite-*"
      testing:
        patterns:
          - "@testing-library/*"
          - "jsdom"
          - "vitest"

  - package-ecosystem: "npm"
    directories:
      - "/examples/*"
    schedule:
      interval: weekly
      day: tuesday
      time: "11:00"
    commit-message:
      include: scope
      prefix: "chore"
      prefix-development: "chore"
    groups:
      expo:
        patterns:
          - "@expo/*"
          - "expo"
          - "expo-*"
          - "eslint-config-expo"
